SimpleX_base:
    model: SimpleX
    dataset_id: TBD
    metrics: ['Precision(k=5)','Precision(k=10)','Precision(k=20)','Precision(k=50)','Precision(k=5)',
              'Recall(k=5)','Recall(k=10)','Recall(k=20)','Recall(k=50)','Recall(k=100)',
              'NDCG(k=5)','NDCG(k=10)','NDCG(k=20)','NDCG(k=50)','NDCG(k=100)',
              'MAP(k=5)','MAP(k=10)','MAP(k=20)','MAP(k=50)','MAP(k=100)',
              'F1(k=5)','F1(k=10)','F1(k=20)','F1(k=50)','F1(k=100)',
              'HitRate(k=5)','HitRate(k=10)','HitRate(k=20)','HitRate(k=50)','HitRate(k=100)']
    optimizer: adam
    learning_rate: 1.0e-3
    batch_size: 1024
    num_negs: 1000
    embedding_dim: 64
    aggregator: mean
    gamma: 0.5
    user_id_field: user_id
    item_id_field: item_id
    user_history_field: user_history
    embedding_regularizer: 0
    net_regularizer: 0
    net_dropout: 0
    attention_dropout: 0
    enable_bias: False
    similarity_score: dot
    loss: PairwiseLogisticLoss
    margin: 0
    negative_weight: null
    sampling_num_process: 1
    fix_sampling_seeds: True
    ignore_pos_items: False
    epochs: 1000
    shuffle: True
    seed: 2019
    monitor: 'Recall(k=20)'
    monitor_mode: 'max'