SimpleX_yelp18_x0_001_704fd7d6:
    aggregator: mean
    attention_dropout: 0
    batch_size: 512
    dataset_id: amazonbooks_x0_9217a019
    debug_mode: false
    embedding_dim: 64
    embedding_regularizer: 1.0e-08
    enable_bias: false
    epochs: 1000
    eval_interval_epochs: 1
    fix_sampling_seeds: false
    gamma: 1
    ignore_pos_items: false
    item_id_field: item_id
    learning_rate: 0.0001
    loss: CosineContrastiveLoss
    margin: 0.9
    metrics: [Recall(k=20), Recall(k=50), NDCG(k=20), NDCG(k=50), HitRate(k=20), MAP(k=50),
        MRR(k=20), F1(k=20)]
    model: SimpleX
    model_id: SimpleX_base
    model_root: ./Yelp18/SimpleX_amazonbooks_x0/
    monitor: Recall(k=20)
    monitor_mode: max
    negative_weight: 150
    net_dropout: 0.1
    net_regularizer: 0
    num_negs: 1000
    num_workers: 3
    optimizer: adam
    patience: 3
    sampling_num_process: 1
    save_best_only: true
    seed: 2019
    shuffle: true
    similarity_score: cosine
    user_history_field: user_history
    user_id_field: user_id
    verbose: 1
