SimpleX_lastfm_x0_001_698ea5d0:
    aggregator: mean
    attention_dropout: 0
    batch_size: 512
    dataset_id: amazonbooks_x0_94bc464c
    debug_mode: false
    embedding_dim: 64
    embedding_regularizer: 1.0e-08
    enable_bias: false
    epochs: 1000
    eval_interval_epochs: 1
    fix_sampling_seeds: false
    gamma: 1
    ignore_pos_items: false
    item_id_field: item_id
    learning_rate: 0.0001
    loss: CosineContrastiveLoss
    margin: 0.9
    metrics: [Precision(k=5), Precision(k=10), Precision(k=20), Precision(k=50), Precision(k=5),
        Recall(k=5), Recall(k=10), Recall(k=20), Recall(k=50), Recall(k=100), NDCG(k=5),
        NDCG(k=10), NDCG(k=20), NDCG(k=50), NDCG(k=100), MAP(k=5), MAP(k=10), MAP(k=20),
        MAP(k=50), MAP(k=100), F1(k=5), F1(k=10), F1(k=20), F1(k=50), F1(k=100), HitRate(k=5),
        HitRate(k=10), HitRate(k=20), HitRate(k=50), HitRate(k=100)]
    model: SimpleX
    model_id: SimpleX_base
    model_root: ./Lastfm/SimpleX_amazonbooks_x0/
    monitor: Recall(k=20)
    monitor_mode: max
    negative_weight: 150
    net_dropout: 0.1
    net_regularizer: 0
    num_negs: 1000
    num_workers: 3
    optimizer: adam
    patience: 3
    sampling_num_process: 1
    save_best_only: true
    seed: 2019
    shuffle: true
    similarity_score: cosine
    user_history_field: user_history
    user_id_field: user_id
    verbose: 1
